Sprint 10
Sherstyankin/java-filmorate pull request #5
Opened 2023-03-16 09:16 UTC by Sherstyankin

feat: добавить фунционал по работе с друзьями пользователей и обработке лайков на фильмы

2023-03-16 12:52 UTC, db-exp requested changes

2023-03-16 12:52 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilms().values();
в идеале из метода storage отдавать коллекцию без раскрытия сервису, что там лежит Map

2023-03-16 12:52 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilms().containsKey(film.getId())) {
и тут тоже можно спрятать contains

2023-03-16 12:52 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilms().get(filmId);
и тут можно спрятать get

2023-03-16 12:52 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUsers().values();
тут так же как и в films хорошо бы скрыть реализацию хранилища

2023-03-16 13:26 UTC, Sherstyankin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilms().values();
То есть лучше спрятать все, что в return в отдельный метод storage?

2023-03-16 18:41 UTC, db-exp requested changes

2023-03-16 18:41 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .andExpect(status().isInternalServerError());
тут и везде, где isInternalServerError(), по идее должно быть isBadRequest() как раньше - из задания
"400 — если ошибка валидации: ValidationException; "

2023-03-17 12:13 UTC, db-exp approved these changes

2023-03-17 16:38 UTC, merged