Add database
Sherstyankin/java-filmorate pull request #7
Opened 2023-04-16 07:54 UTC by Sherstyankin

Интеграционные тесты еще не готовы. Решил сначала основной код на ревью отправить. ER-диграмма уже в main (см. ветку add-er-diagram).

2023-04-16 20:51 UTC, db-exp requested changes

2023-04-16 20:51 UTC, db-exp commented on src/main/resources/schema.sql
> +	email varchar(255) NOT NULL,
много для почты

2023-04-16 20:51 UTC, db-exp commented on src/main/resources/schema.sql
> +	login varchar(255) NOT NULL,
много для логина

2023-04-16 20:51 UTC, db-exp commented on src/main/resources/application.properties
> +//spring.datasource.url=jdbc:h2:file:./db/filmorate
комментарий в проперти так не работает) 
Тут надо через '#'

2023-04-16 20:51 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Collection<Film> getAllFilms() {
В идеале тут и ниже перейти от вовзращения модели к Dto объекту FilmDto

2023-04-16 20:51 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
>          if (id == null) {
эту проверку можно повесить на параметр https://stackoverflow.com/questions/24582842/is-it-possible-to-validate-requestparam-in-spring-mvc-rest-endpoint

2023-04-16 20:54 UTC, db-exp commented
+ не хватает схемы для БД

2023-04-17 07:50 UTC, Sherstyankin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Collection<Film> getAllFilms() {
Извини, не совсем понял. А какие поля урезать у модели (для dto)? У нас же на все поля проверки в Postman тестах, кроме лайков (их из модели я уже убрал).

2023-04-19 05:52 UTC, Sherstyankin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Collection<Film> getAllFilms() {
Добавил тесты. Исправил замечания.

2023-04-19 17:05 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
>                      " указана некорректно.");
напомню на всякий случай, что можно сделать кастомную валидацию https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-04-19 17:41 UTC, db-exp approved these changes

2023-04-21 10:58 UTC, Sherstyankin commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
>                      " указана некорректно.");
Спасибо за рекомендацию!

2023-04-21 10:58 UTC, merged